package main

import (
	"errors"
	"regexp"
)

func AppStoreSetting(domain string) (AppStoreID, error) {
	var appStoreSettings = map[string]AppStoreID{
		"ae": AppStoreID{CountryDomain: "ae", CountryName: "United Arab Emirates", CountryCode: "143481"},
		"ag": AppStoreID{CountryDomain: "ag", CountryName: "Antigua and Barbuda", CountryCode: "143540"},
		"ai": AppStoreID{CountryDomain: "ai", CountryName: "Anguilla", CountryCode: "143538"},
		"al": AppStoreID{CountryDomain: "al", CountryName: "Albania", CountryCode: "143575"},
		"am": AppStoreID{CountryDomain: "am", CountryName: "Armenia", CountryCode: "143524"},
		"ao": AppStoreID{CountryDomain: "ao", CountryName: "Angola", CountryCode: "143564"},
		"ar": AppStoreID{CountryDomain: "ar", CountryName: "Argentina", CountryCode: "143505"},
		"at": AppStoreID{CountryDomain: "at", CountryName: "Austria", CountryCode: "143445"},
		"au": AppStoreID{CountryDomain: "au", CountryName: "Australia", CountryCode: "143460"},
		"az": AppStoreID{CountryDomain: "az", CountryName: "Azerbaijan", CountryCode: "143568"},
		"bb": AppStoreID{CountryDomain: "bb", CountryName: "Barbados", CountryCode: "143541"},
		"be": AppStoreID{CountryDomain: "be", CountryName: "Belgium", CountryCode: "143446"},
		"bf": AppStoreID{CountryDomain: "bf", CountryName: "Burkina Faso", CountryCode: "143578"},
		"bg": AppStoreID{CountryDomain: "bg", CountryName: "Bulgaria", CountryCode: "143526"},
		"bh": AppStoreID{CountryDomain: "bh", CountryName: "Bahrain", CountryCode: "143559"},
		"bj": AppStoreID{CountryDomain: "bj", CountryName: "Benin", CountryCode: "143576"},
		"bm": AppStoreID{CountryDomain: "bm", CountryName: "Bermuda", CountryCode: "143542"},
		"bn": AppStoreID{CountryDomain: "bn", CountryName: "Brunei", CountryCode: "143560"},
		"bo": AppStoreID{CountryDomain: "bo", CountryName: "Bolivia", CountryCode: "143556"},
		"br": AppStoreID{CountryDomain: "br", CountryName: "Brazil", CountryCode: "143503"},
		"bs": AppStoreID{CountryDomain: "bs", CountryName: "Bahamas", CountryCode: "143539"},
		"bt": AppStoreID{CountryDomain: "bt", CountryName: "Bhutan", CountryCode: "143577"},
		"bw": AppStoreID{CountryDomain: "bw", CountryName: "Botswana", CountryCode: "143525"},
		"by": AppStoreID{CountryDomain: "by", CountryName: "Belarus", CountryCode: "143565"},
		"bz": AppStoreID{CountryDomain: "bz", CountryName: "Belize", CountryCode: "143555"},
		"ca": AppStoreID{CountryDomain: "ca", CountryName: "Canada", CountryCode: "143455"},
		"cg": AppStoreID{CountryDomain: "cg", CountryName: "Republic Of Congo", CountryCode: "143582"},
		"ch": AppStoreID{CountryDomain: "ch", CountryName: "Switzerland", CountryCode: "143459"},
		"cl": AppStoreID{CountryDomain: "cl", CountryName: "Chile", CountryCode: "143483"},
		"cn": AppStoreID{CountryDomain: "cn", CountryName: "China", CountryCode: "143465"},
		"co": AppStoreID{CountryDomain: "co", CountryName: "Colombia", CountryCode: "143501"},
		"cr": AppStoreID{CountryDomain: "cr", CountryName: "Costa Rica", CountryCode: "143495"},
		"cv": AppStoreID{CountryDomain: "cv", CountryName: "Cape Verde", CountryCode: "143580"},
		"cy": AppStoreID{CountryDomain: "cy", CountryName: "Cyprus", CountryCode: "143557"},
		"cz": AppStoreID{CountryDomain: "cz", CountryName: "Czech Republic", CountryCode: "143489"},
		"de": AppStoreID{CountryDomain: "de", CountryName: "Germany", CountryCode: "143443"},
		"dk": AppStoreID{CountryDomain: "dk", CountryName: "Denmark", CountryCode: "143458"},
		"dm": AppStoreID{CountryDomain: "dm", CountryName: "Dominica", CountryCode: "143545"},
		"do": AppStoreID{CountryDomain: "do", CountryName: "Dominican Republic", CountryCode: "143508"},
		"dz": AppStoreID{CountryDomain: "dz", CountryName: "Algeria", CountryCode: "143563"},
		"ec": AppStoreID{CountryDomain: "ec", CountryName: "Ecuador", CountryCode: "143509"},
		"ee": AppStoreID{CountryDomain: "ee", CountryName: "Estonia", CountryCode: "143518"},
		"eg": AppStoreID{CountryDomain: "eg", CountryName: "Egypt", CountryCode: "143516"},
		"es": AppStoreID{CountryDomain: "es", CountryName: "Spain", CountryCode: "143454"},
		"fi": AppStoreID{CountryDomain: "fi", CountryName: "Finland", CountryCode: "143447"},
		"fj": AppStoreID{CountryDomain: "fj", CountryName: "Fiji", CountryCode: "143583"},
		"fm": AppStoreID{CountryDomain: "fm", CountryName: "Federated States Of Micronesia", CountryCode: "143591"},
		"fr": AppStoreID{CountryDomain: "fr", CountryName: "France", CountryCode: "143442"},
		"gb": AppStoreID{CountryDomain: "gb", CountryName: "United Kingdom", CountryCode: "143444"},
		"gd": AppStoreID{CountryDomain: "gd", CountryName: "Grenada", CountryCode: "143546"},
		"gh": AppStoreID{CountryDomain: "gh", CountryName: "Ghana", CountryCode: "143573"},
		"gm": AppStoreID{CountryDomain: "gm", CountryName: "Gambia", CountryCode: "143584"},
		"gr": AppStoreID{CountryDomain: "gr", CountryName: "Greece", CountryCode: "143448"},
		"gt": AppStoreID{CountryDomain: "gt", CountryName: "Guatemala", CountryCode: "143504"},
		"gw": AppStoreID{CountryDomain: "gw", CountryName: "Guinea-Bissau", CountryCode: "143585"},
		"gy": AppStoreID{CountryDomain: "gy", CountryName: "Guyana", CountryCode: "143553"},
		"hk": AppStoreID{CountryDomain: "hk", CountryName: "Hong Kong", CountryCode: "143463"},
		"hn": AppStoreID{CountryDomain: "hn", CountryName: "Honduras", CountryCode: "143510"},
		"hr": AppStoreID{CountryDomain: "hr", CountryName: "Croatia", CountryCode: "143494"},
		"hu": AppStoreID{CountryDomain: "hu", CountryName: "Hungary", CountryCode: "143482"},
		"id": AppStoreID{CountryDomain: "id", CountryName: "Indonesia", CountryCode: "143476"},
		"ie": AppStoreID{CountryDomain: "ie", CountryName: "Ireland", CountryCode: "143449"},
		"il": AppStoreID{CountryDomain: "il", CountryName: "Israel", CountryCode: "143491"},
		"in": AppStoreID{CountryDomain: "in", CountryName: "India", CountryCode: "143467"},
		"is": AppStoreID{CountryDomain: "is", CountryName: "Iceland", CountryCode: "143558"},
		"it": AppStoreID{CountryDomain: "it", CountryName: "Italy", CountryCode: "143450"},
		"jm": AppStoreID{CountryDomain: "jm", CountryName: "Jamaica", CountryCode: "143511"},
		"jo": AppStoreID{CountryDomain: "jo", CountryName: "Jordan", CountryCode: "143528"},
		"jp": AppStoreID{CountryDomain: "jp", CountryName: "Japan", CountryCode: "143462"},
		"ke": AppStoreID{CountryDomain: "ke", CountryName: "Kenya", CountryCode: "143529"},
		"kg": AppStoreID{CountryDomain: "kg", CountryName: "Kyrgyzstan", CountryCode: "143586"},
		"kh": AppStoreID{CountryDomain: "kh", CountryName: "Cambodia", CountryCode: "143579"},
		"kn": AppStoreID{CountryDomain: "kn", CountryName: "St. Kitts and Nevis", CountryCode: "143548"},
		"kr": AppStoreID{CountryDomain: "kr", CountryName: "Republic Of Korea", CountryCode: "143466"},
		"kw": AppStoreID{CountryDomain: "kw", CountryName: "Kuwait", CountryCode: "143493"},
		"ky": AppStoreID{CountryDomain: "ky", CountryName: "Cayman Islands", CountryCode: "143531"},
		"kz": AppStoreID{CountryDomain: "kz", CountryName: "Kazakstan", CountryCode: "143517"},
		"la": AppStoreID{CountryDomain: "la", CountryName: "Lao People’s Democratic Republic", CountryCode: "143587"},
		"lb": AppStoreID{CountryDomain: "lb", CountryName: "Lebanon", CountryCode: "143497"},
		"lc": AppStoreID{CountryDomain: "lc", CountryName: "St. Lucia", CountryCode: "143549"},
		"lk": AppStoreID{CountryDomain: "lk", CountryName: "Sri Lanka", CountryCode: "143486"},
		"lr": AppStoreID{CountryDomain: "lr", CountryName: "Liberia", CountryCode: "143588"},
		"lt": AppStoreID{CountryDomain: "lt", CountryName: "Lithuania", CountryCode: "143520"},
		"lu": AppStoreID{CountryDomain: "lu", CountryName: "Luxembourg", CountryCode: "143451"},
		"lv": AppStoreID{CountryDomain: "lv", CountryName: "Latvia", CountryCode: "143519"},
		"md": AppStoreID{CountryDomain: "md", CountryName: "Republic Of Moldova", CountryCode: "143523"},
		"mg": AppStoreID{CountryDomain: "mg", CountryName: "Madagascar", CountryCode: "143531"},
		"mk": AppStoreID{CountryDomain: "mk", CountryName: "Macedonia", CountryCode: "143530"},
		"ml": AppStoreID{CountryDomain: "ml", CountryName: "Mali", CountryCode: "143532"},
		"mn": AppStoreID{CountryDomain: "mn", CountryName: "Mongolia", CountryCode: "143592"},
		"mo": AppStoreID{CountryDomain: "mo", CountryName: "Macau", CountryCode: "143515"},
		"mr": AppStoreID{CountryDomain: "mr", CountryName: "Mauritania", CountryCode: "143590"},
		"ms": AppStoreID{CountryDomain: "ms", CountryName: "Montserrat", CountryCode: "143547"},
		"mt": AppStoreID{CountryDomain: "mt", CountryName: "Malta", CountryCode: "143521"},
		"mu": AppStoreID{CountryDomain: "mu", CountryName: "Mauritius", CountryCode: "143533"},
		"mw": AppStoreID{CountryDomain: "mw", CountryName: "Malawi", CountryCode: "143589"},
		"mx": AppStoreID{CountryDomain: "mx", CountryName: "Mexico", CountryCode: "143468"},
		"my": AppStoreID{CountryDomain: "my", CountryName: "Malaysia", CountryCode: "143473"},
		"mz": AppStoreID{CountryDomain: "mz", CountryName: "Mozambique", CountryCode: "143593"},
		"na": AppStoreID{CountryDomain: "na", CountryName: "Namibia", CountryCode: "143594"},
		"ne": AppStoreID{CountryDomain: "ne", CountryName: "Niger", CountryCode: "143534"},
		"ng": AppStoreID{CountryDomain: "ng", CountryName: "Nigeria", CountryCode: "143561"},
		"ni": AppStoreID{CountryDomain: "ni", CountryName: "Nicaragua", CountryCode: "143512"},
		"nl": AppStoreID{CountryDomain: "nl", CountryName: "Netherlands", CountryCode: "143452"},
		"no": AppStoreID{CountryDomain: "no", CountryName: "Norway", CountryCode: "143457"},
		"np": AppStoreID{CountryDomain: "np", CountryName: "Nepal", CountryCode: "143484"},
		"nz": AppStoreID{CountryDomain: "nz", CountryName: "New Zealand", CountryCode: "143461"},
		"om": AppStoreID{CountryDomain: "om", CountryName: "Oman", CountryCode: "143562"},
		"pa": AppStoreID{CountryDomain: "pa", CountryName: "Panama", CountryCode: "143485"},
		"pe": AppStoreID{CountryDomain: "pe", CountryName: "Peru", CountryCode: "143507"},
		"pg": AppStoreID{CountryDomain: "pg", CountryName: "Papua New Guinea", CountryCode: "143597"},
		"ph": AppStoreID{CountryDomain: "ph", CountryName: "Philippines", CountryCode: "143474"},
		"pk": AppStoreID{CountryDomain: "pk", CountryName: "Pakistan", CountryCode: "143477"},
		"pl": AppStoreID{CountryDomain: "pl", CountryName: "Poland", CountryCode: "143478"},
		"pt": AppStoreID{CountryDomain: "pt", CountryName: "Portugal", CountryCode: "143453"},
		"pw": AppStoreID{CountryDomain: "pw", CountryName: "Palau", CountryCode: "143595"},
		"py": AppStoreID{CountryDomain: "py", CountryName: "Paraguay", CountryCode: "143513"},
		"qa": AppStoreID{CountryDomain: "qa", CountryName: "Qatar", CountryCode: "143498"},
		"ro": AppStoreID{CountryDomain: "ro", CountryName: "Romania", CountryCode: "143487"},
		"ru": AppStoreID{CountryDomain: "ru", CountryName: "Russia", CountryCode: "143469"},
		"sa": AppStoreID{CountryDomain: "sa", CountryName: "Saudi Arabia", CountryCode: "143479"},
		"sb": AppStoreID{CountryDomain: "sb", CountryName: "Solomon Islands", CountryCode: "143601"},
		"sc": AppStoreID{CountryDomain: "sc", CountryName: "Seychelles", CountryCode: "143599"},
		"se": AppStoreID{CountryDomain: "se", CountryName: "Sweden", CountryCode: "143456"},
		"sg": AppStoreID{CountryDomain: "sg", CountryName: "Singapore", CountryCode: "143464"},
		"si": AppStoreID{CountryDomain: "si", CountryName: "Slovenia", CountryCode: "143499"},
		"sk": AppStoreID{CountryDomain: "sk", CountryName: "Slovakia", CountryCode: "143496"},
		"sl": AppStoreID{CountryDomain: "sl", CountryName: "Sierra Leone", CountryCode: "143600"},
		"sn": AppStoreID{CountryDomain: "sn", CountryName: "Senegal", CountryCode: "143535"},
		"sr": AppStoreID{CountryDomain: "sr", CountryName: "Suriname", CountryCode: "143554"},
		"st": AppStoreID{CountryDomain: "st", CountryName: "Sao Tome and Principe", CountryCode: "143598"},
		"sv": AppStoreID{CountryDomain: "sv", CountryName: "El Salvador", CountryCode: "143506"},
		"sz": AppStoreID{CountryDomain: "sz", CountryName: "Swaziland", CountryCode: "143602"},
		"tc": AppStoreID{CountryDomain: "tc", CountryName: "Turks and Caicos", CountryCode: "143552"},
		"td": AppStoreID{CountryDomain: "td", CountryName: "Chad", CountryCode: "143581"},
		"th": AppStoreID{CountryDomain: "th", CountryName: "Thailand", CountryCode: "143475"},
		"tj": AppStoreID{CountryDomain: "tj", CountryName: "Tajikistan", CountryCode: "143603"},
		"tm": AppStoreID{CountryDomain: "tm", CountryName: "Turkmenistan", CountryCode: "143604"},
		"tn": AppStoreID{CountryDomain: "tn", CountryName: "Tunisia", CountryCode: "143536"},
		"tr": AppStoreID{CountryDomain: "tr", CountryName: "Turkey", CountryCode: "143480"},
		"tt": AppStoreID{CountryDomain: "tt", CountryName: "Trinidad and Tobago", CountryCode: "143551"},
		"tw": AppStoreID{CountryDomain: "tw", CountryName: "Taiwan", CountryCode: "143470"},
		"tz": AppStoreID{CountryDomain: "tz", CountryName: "Tanzania", CountryCode: "143572"},
		"ua": AppStoreID{CountryDomain: "ua", CountryName: "Ukraine", CountryCode: "143492"},
		"ug": AppStoreID{CountryDomain: "ug", CountryName: "Uganda", CountryCode: "143537"},
		"us": AppStoreID{CountryDomain: "us", CountryName: "United States", CountryCode: "143441"},
		"uy": AppStoreID{CountryDomain: "uy", CountryName: "Uruguay", CountryCode: "143514"},
		"uz": AppStoreID{CountryDomain: "uz", CountryName: "Uzbekistan", CountryCode: "143566"},
		"vc": AppStoreID{CountryDomain: "vc", CountryName: "St. Vincent and The Grenadines", CountryCode: "143550"},
		"ve": AppStoreID{CountryDomain: "ve", CountryName: "Venezuela", CountryCode: "143502"},
		"vg": AppStoreID{CountryDomain: "vg", CountryName: "British Virgin Islands", CountryCode: "143543"},
		"vn": AppStoreID{CountryDomain: "vn", CountryName: "Vietnam", CountryCode: "143471"},
		"ye": AppStoreID{CountryDomain: "ye", CountryName: "Yemen", CountryCode: "143571"},
		"za": AppStoreID{CountryDomain: "za", CountryName: "South Africa", CountryCode: "143472"},
		"zw": AppStoreID{CountryDomain: "zw", CountryName: "Zimbabwe", CountryCode: "143605"},
	}
	appStoreSetting, ok := appStoreSettings[domain]
	if ok != true {
		return AppStoreID{}, errors.New("cannot find country domain")
	}
	return appStoreSetting, nil
}

func parseURL(url string) (string, string, error) {
	regexURL := regexp.MustCompile(`https://itunes.apple.com/([a-zA-Z]{2})/app/id(\d+)`)
	result := regexURL.FindStringSubmatch(url)
	appStoreSetting, err := AppStoreSetting(result[1])
	if err != nil {
		return "", "", errors.New("invalid url")
	}
	return result[2], appStoreSetting.CountryCode, nil
}
